baseURL = 'https://your-site.pages.dev'
languageCode = 'zh-tw'
title = '專業會計事務所'
theme = 'apple-style'

# 建置設定
buildFuture = false
buildDrafts = false
buildExpired = false

# 分頁設定
paginate = 12
paginatePath = "page"

# 多語言支援
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = false

[params]
  # 網站基本資訊
  description = "專業的會計、稅務、創業諮詢服務，您值得信賴的財務夥伴"
  keywords = "會計師,稅務,創業,公司設立,記帳,財務規劃"
  author = "專業會計師團隊"
  
  # 聯絡資訊
  phone = "02-1234-5678"
  email = "info@your-domain.com"
  address = "台北市信義區信義路五段7號"
  
  # 社群媒體
  facebook = "https://facebook.com/your-page"
  line = "https://line.me/ti/p/your-line-id"
  
  # 預約發布設定
  scheduledPublishing = true
  timezone = "Asia/Taipei"
  
  # Google Analytics
  googleAnalytics = "G-XXXXXXXXXX"
  
  # SEO 設定
  images = ["/images/og-image.jpg"]

[frontmatter]
  publishDate = "publishDate"
  lastmod = ":fileModTime"
  date = "date"
  expiryDate = "expiryDate"

[permalinks]
  articles = "/articles/:sections[1:]/:slug/"
  videos = "/videos/:sections[1:]/:slug/"
  faq = "/faq/:sections[1:]/:slug/"
  downloads = "/downloads/:sections[1:]/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true
    guessSyntax = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[privacy]
  [privacy.googleAnalytics]
    respectDoNotTrack = true

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']

[imaging]
  resampleFilter = "CatmullRom"
  quality = 85
  anchor = "smart"

# 選單定義
[menu]
  [[menu.main]]
    name = "首頁"
    url = "/"
    weight = 10
    
  [[menu.main]]
    name = "關於我們"
    url = "/about/"
    weight = 20
    
  [[menu.main]]
    name = "服務項目"
    url = "/services/"
    weight = 30
    
  [[menu.main]]
    name = "知識文章"
    url = "/articles/"
    weight = 40
    
  [[menu.main]]
    name = "影音專區"
    url = "/videos/"
    weight = 50
    
  [[menu.main]]
    name = "常見問題"
    url = "/faq/"
    weight = 60
    
  [[menu.main]]
    name = "下載專區"
    url = "/downloads/"
    weight = 70
    
  [[menu.main]]
    name = "聯絡我們"
    url = "/contact/"
    weight = 80
    
  [[menu.main]]
    name = "預約諮詢"
    url = "/appointment/"
    weight = 90
    pre = "cta"
