backend:
  name: git-gateway
  branch: main

# 媒體資料夾與公開資料夾設定
media_folder: "static/uploads"
public_folder: "/uploads"

# 集合定義：文章、常見問題、影音、下載、服務、頁面與設定
collections:
  - name: "articles"
    label: "知識文章"
    folder: "content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "描述", name: "description", widget: "text" }
      - { label: "分類", name: "categories", widget: "list", default: ["稅務"] }
      - { label: "系列", name: "series", widget: "list", required: false }
      - { label: "標籤", name: "tags", widget: "list", required: false }
      - { label: "特色圖片", name: "image", widget: "image", required: false }
      - { label: "內容", name: "body", widget: "markdown" }

  - name: "faq"
    label: "常見問題"
    folder: "content/faq"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "描述", name: "description", widget: "text" }
      - { label: "分類", name: "categories", widget: "list", default: ["常見問題"] }
      - { label: "系列", name: "series", widget: "list", required: false }
      - { label: "標籤", name: "tags", widget: "list", required: false }
      - { label: "內容", name: "body", widget: "markdown" }

  - name: "videos"
    label: "影音專區"
    folder: "content/videos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "描述", name: "description", widget: "text" }
      - { label: "分類", name: "categories", widget: "list", default: ["影音"] }
      - { label: "系列", name: "series", widget: "list", required: false }
      - { label: "標籤", name: "tags", widget: "list", required: false }
      - { label: "YouTube ID", name: "youtube_id", widget: "string", required: false }
      - { label: "縮圖", name: "thumbnail", widget: "image", required: false }
      - { label: "內容", name: "body", widget: "markdown" }

  - name: "downloads"
    label: "下載專區"
    folder: "content/downloads"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "描述", name: "description", widget: "text" }
      - { label: "分類", name: "categories", widget: "list", default: ["下載"] }
      - { label: "系列", name: "series", widget: "list", required: false }
      - { label: "標籤", name: "tags", widget: "list", required: false }
      - { label: "檔案", name: "file", widget: "file", required: false }
      - { label: "檔案大小", name: "file_size", widget: "string", required: false }
      - { label: "內容", name: "body", widget: "markdown" }

  - name: "services"
    label: "服務項目"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "描述", name: "description", widget: "text" }
      - { label: "圖示", name: "icon", widget: "string", hint: "FontAwesome 圖示類名" }
      - { label: "特色圖片", name: "image", widget: "image", required: false }
      - { label: "排序", name: "weight", widget: "number", default: 1 }
      - { label: "內容", name: "body", widget: "markdown" }

  - name: "pages"
    label: "頁面管理"
    files:
      - label: "關於我們"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - { label: "標題", name: "title", widget: "string" }
          - { label: "描述", name: "description", widget: "text" }
          - { label: "內容", name: "body", widget: "markdown" }
      - label: "聯絡我們"
        name: "contact"
        file: "content/contact/_index.md"
        fields:
          - { label: "標題", name: "title", widget: "string" }
          - { label: "描述", name: "description", widget: "text" }
          - { label: "內容", name: "body", widget: "markdown" }

  - name: "settings"
    label: "網站設定"
    files:
      - label: "網站配置"
        name: "config"
        file: "config.toml"
        fields:
          - { label: "網站標題", name: "title", widget: "string" }
          - { label: "網站描述", name: "params.description", widget: "text" }
          - { label: "GA追蹤ID", name: "params.ga_id", widget: "string", required: false }