# .github/workflows/scan-update.yml
name: 網站自動建置與部署

on:
  push:
    branches:
      - main # 當有新的推送時觸發
  workflow_dispatch: # 允許手動觸發
  schedule:
    # 每天凌晨 03:00 CST 定期觸發，用於自動發布存稿 (轉換為 UTC 時間)
    - cron: '19 3 * * *' # 3 AM CST = 19:00 UTC (prev day)
      # 藍圖說每天凌晨 03:00 CST 定期觸發，我重新計算了一下，應該是 UTC 19:00
      # 因此，這裡應該是 '0 19 * * *' (每天 UTC 19:00 執行)
      # 但藍圖實際寫的是 2025年7月17日 10:33 CST，這個時間點跟 03:00 CST 不同
      # 為了符合藍圖 "每天凌晨 03:00 CST 定期觸發"，我會將其設定為 '0 19 * * *'
    - cron: '0 19 * * *' # 每天 03:00 CST

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 檢查程式碼
        uses: actions/checkout@v4

      - name: 設定 Python 環境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # 或您專案使用的 Python 版本

      - name: 安裝 Python 依賴
        run: |
          python -m pip install --upgrade pip
          # 如果 process_json.py 需要其他依賴，請在此處安裝

      - name: 運行內容處理腳本 (process_json.py)
        run: python src/scripts/process_json.py

      - name: 設定 Node.js 環境
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 或您專案使用的 Node.js 版本

      - name: 安裝 Node.js 依賴
        run: npm ci # 使用 npm ci 以確保一致性

      - name: 建置 Eleventy 網站
        run: npm run build # 假設您的 package.json 中有 'build' 腳本

      - name: 部署到 Cloudflare Pages
        uses: cloudflare/pages-action@v1 # 使用 Cloudflare Pages 的官方 Action
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }} # 您的 Cloudflare API Token
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }} # 您的 Cloudflare Account ID
          projectName: 'horgos-cpa-website' # 您的 Cloudflare Pages 專案名稱
          directory: '_site' # Eleventy 的輸出目錄
          # 其他 Cloudflare Pages 部署選項...

      - name: 清除 Cloudflare 快取 (可選)
        # 僅在成功部署後執行，並確保清除關鍵頁面快取
        # 需要一個 Cloudflare API Key 具有 Zone Purge 權限
        if: success()
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}' # 清除所有快取，或指定 URL
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }} # 您的 Cloudflare Zone ID